### ISSUE TITLE
How to test locally with dummy data?

### ISSUE THREAD

**Issue by checor** [maizzle/docs#26]
Hello,

I'm a new user of Maizzle, and maybe this is more related to Nunjucks than to the docs or this framework.

I've made a template as stated on the docs, I can see it with `maizzle serve` and I want to see my template with some dummy data, is there a way I can do it? I can't find in the docs how to do it.

Keep up the good work!

**Comment by cossssmin** [comment]
Hi there!

Not sure I understand, are you looking to pull some dummy data from somewhere, or...?

**Comment by checor** [comment]
I have a local .json file that I want to use as the context of an email, for test purposes.

The thing I figured out was reading the file in config.js and add the variable to the exported module:

```
const fs = require('fs');

let rawdata = fs.readFileSync('src/assets/dummy/purchase.json');
let purchase = JSON.parse(rawdata);

module.exports = {
    ...
   purchase: purchase,
   ...
}
```

The I read the variable in the email template:

```
{{ page.purchase.first_name }}
```

Is there a better way to achieve this? The info doesn't need to be in the .json, but I want a for to see my template with test data.

**Comment by cossssmin** [comment]
Nope, that's exactly how you do it 👍

Alternatively you could define it as a self-invoking function that returns the JSON:

```
module.exports = {
  purchase: function() {
    return JSON.parse(fs.readFileSync('src/assets/dummy/purchase.json'));
  }(),
}
```

**Comment by checor** [comment]
Thanks for the help!

If you want, I can help adding this information to the docs, if you find it relevant for beginners.

**Comment by cossssmin** [comment]
Functions are mentioned [here](https://maizzle.com/docs/functions/#functions), but if you can think of a place where we could offer a better explanation, I'm open to PRs. Maybe in the examples section?
