### ISSUE TITLE
Guidance on how to integrate with handlebars (or similar) for email service sending

### ISSUE THREAD

**Issue by dhritzkiv** [maizzle/docs#39]
Many email services support storing a template in their system and passing in JSON data to fill out the template with content at send-time. Unfortunately, no services seem to support nunjucks as a template language, and instead support something like Handlebars (Mandrill, SendGrid come to mind).

Is there a recommended way to compile the nunjuck template, and output a file with the template file of the template language of choice (e.g. handlebars) left in? Ideally, this would also work during development with the Browsersync UI, where test/dummy data can be passed in to render with e.g. handlebars.

I'm aware of `{% raw %}` and some of the post render events, but I'm still struggling on how to use those to achieve what I and many others are looking for.

I think a complete solution in maizzle would be beneficial for helping with automatically testing and deploying templates to third-party services.

Related comments/threads:
- https://github.com/maizzle/framework/issues/28#issuecomment-516387300
- https://github.com/maizzle/docs/issues/26
- https://github.com/maizzle/framework/issues/62

**Comment by cossssmin** [comment]
`{% raw %}` is the recommended solution, although you could also customize the tags that Nunjucks uses, as documented [here](https://maizzle.com/docs/build-paths/#nunjucks).

I can write a guide on how to use both approaches - I actually have a tutorial planned for using Maizzle alongside a framework like Laravel, where the Blade templating language also uses `{{ }}` 👍

**Comment by cossssmin** [comment]
Gonna hold off the tutorial I mentioned, I plan on switching from Nunjucks to PostHTML (once we have filters in `posthtml-expressions`, like we now in Nunjucks).

In the meantime, just use `{% raw %}` with Nunjucks.

With PostHTML, you'll be able to use `<raw></raw>` and `@{{ }}` (Laravel-like).

**Comment by dhritzkiv** [comment]
That's cool.

FWIW, my solution was to not use the `{% raw %}` tags, but instead to:
- use custom nunjuck tags (e.g. `[[ ]]` instead of `{{ }}`, etc.) so they don't conflict with handlebars);
- write handlebars code in the template directly;
-  pass the post-nunjuck rendered HTML to handlebars inside of the post-render hook function in the config

This way, my template code renders the same in development as it does in production when sending it to e.g. Sendgrid. It's not perfect, and doesn't easily scale, but it works well enough to give me peace of mind.

**Comment by akshay-nm** [comment]
> Gonna hold off the tutorial I mentioned, I plan on switching from Nunjucks to PostHTML (once we have filters in `posthtml-expressions`, like we do now in Nunjucks).
> 
> In the meantime, just use `{% raw %}` with Nunjucks.
> 
> With PostHTML, you'll be able to use `<raw></raw>` and `@{{ }}` (Laravel-like).

I am new to POST HTML and didn't know how to get something like `{{ ABC }}` in the build output. More on this: https://github.com/posthtml/posthtml-expressions#ignored-tag
