### ISSUE TITLE
Broken links for build destination and extension

### ISSUE THREAD

**Issue by connecteev** [maizzle/docs#67]
I was trying to find a way to configure the extension after the build process completes.
There are 2 broken links here:
https://maizzle.com/docs/build-process/

https://maizzle.com/docs/build-paths/#destination
https://maizzle.com/docs/build-paths/#extension

What is the config for doing this? I'd like to save the emails in xxx.blade.php format (will be used in a laravel php app).

**Comment by cossssmin** [comment]
Thanks for reporting this, I've fixed the links 👍

**Comment by connecteev** [comment]
thanks, and youre welcome!
