### ISSUE TITLE
Adding AMP4EMAIL validator to the docs.

### ISSUE THREAD

**Issue by jrtderonde** [maizzle/docs#82]
Resubmission of https://github.com/maizzle/framework/issues/228

**Comment by cossssmin** [comment]
Hey, sorry if there was any confusion, I replied in the original issue that you linked to.

To avoid confusion, I'll close this issue and transfer that one to this repo, so we continue the conversation there. Let me know if you need any help!

**Comment by dominic9043** [comment]
Hello, 

Hope you're well. I tried to find another way to message you but had no luck.  

I wanted to ask you a question about an issue you had with the APDS Gesture sensor. I had the same problem. When I took your advice and changed to LEDBoost100 it started to recognise but will mainly show "None" (Which you also had a problem with) Then saw you fixed this by changing GGain_X2 ... But I cant seem to find it in the h. File.. 

What do I change and where do I find it ? I hope to hear from you... If you could provide me with your email. I could email you. 

Many Thanks, 
Dom
